{{- if .Values.cpa.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-overprovisioner.cpa.serviceAccountName" . }}
  labels:
    {{- include "cluster-overprovisioner.cpa.labels" . | nindent 4 }}
  {{- with .Values.cpa.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
