{{- if and .Values.op.serviceAccount.create .Values.op.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-overprovisioner.op.serviceAccountName" . }}
  labels:
    {{- include "cluster-overprovisioner.op.labels" . | nindent 4 }}
  {{- with .Values.op.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.op.serviceAccount.automountServiceAccountToken }}
{{- end }}
